library(dplyr)
library(patchwork)
library(Seurat)
library(cowplot)
setwd("c:/Users/xjmik/Downloads/GSE140228/")
pbmc1.data<-Read10X("10X/Seurat/")
pbmc.data<-read.csv("smartseq/GSE140228_read_counts_Smartseq2.csv",header = TRUE,row.names = 1,check.names = FALSE)
pbmc.metadata<-read.table("smartseq/GSE140228_cell_info_Smartseq2.tsv",sep = "\t",header = TRUE,row.names = 1)
pbmc1.metadata<-read.table("10X/GSE140228_UMI_counts_Droplet_cellinfo.tsv",sep = "\t",header = TRUE,row.names = 1)
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "IMMUNE_pbmc", min.cells = 5,meta.data = pbmc.metadata)
remove(pbmc.data,pbmc.metadata)
pbmc$type <- "pbmc"
pbmc <- subset(pbmc, subset = nFeature_RNA > 500)
pbmc <- NormalizeData(pbmc, verbose = FALSE)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

pbmc1 <- CreateSeuratObject(counts = pbmc1.data, project = "IMMUNE_pbmc1", min.cells = 5,meta.data = pbmc1.metadata)
remove(pbmc1.data,pbmc1.metadata)
pbmc1$type <- "pbmc1"
pbmc1 <- subset(pbmc1, subset = nFeature_RNA > 500)
pbmc1 <- NormalizeData(pbmc1, verbose = FALSE)
pbmc1 <- FindVariableFeatures(pbmc1, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc1)
pbmc1 <- ScaleData(pbmc1, features = all.genes)

immune.anchors <- FindIntegrationAnchors(object.list = list(pbmc, pbmc1), dims = 1:20)
remove(pbmc,pbmc1)
immune.combined <- IntegrateData(anchorset = immune.anchors, dims = 1:20)
remove(immune.anchors)
DefaultAssay(immune.combined) <- "integrated"
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- ScaleData(immune.combined,assay = "RNA")
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)

immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:20)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:20)
immune.combined <- FindClusters(immune.combined, resolution = 0.8)
DimPlot(immune.combined)
Idents(immune.combined)<-immune.combined@meta.data$celltype_sub
DimPlot(immune.combined)
immune.combined<-RunLDA(immune.combined,assay = "integrated",labels = immune.combined$celltype_sub,features = rownames(immune.combined@assays$integrated))
immune.combined<-RunLDA(immune.combined,assay = "RNA",labels = immune.combined$celltype_sub,features = rownames(immune.combined@assays$RNA),reduction.name = "LDA_RNA")
remove(all.genes,pbmc1.data,pbmc1.metadata,pbmc.data,pbmc.metadata)

immune.combined<-RunUMAP(immune.combined,reduction = "lda",reduction.name = "lda_umap",dims = 1:41)
immune.combined<-RunTSNE(immune.combined,reduction = "lda",reduction.name = "lda_tsne",dims = 1:41)
immune.combined <- RunTSNE(immune.combined, reduction = "pca", dims = 1:20)
DimPlot(immune.combined,reduction = "tsne")
DimPlot(immune.combined,reduction = "lda_umap")
DimPlot(immune.combined,reduction = "lda_tsne")
immune.combined_T<-subset(immune.combined,idents =   "Tumor")
Idents(immune.combined_T)<-immune.combined_T$celltype_sub
DimPlot(immune.combined_T)
immune.combined_T.markers_RNA<-FindAllMarkers(immune.combined_T,only.pos = TRUE,assay = "RNA")
